from fastapi import APIRouter
from pydantic import BaseModel

import os
import sys

# ----------------------------------
# Add project root and ML directory
# ----------------------------------

ROOT = os.path.abspath(
    os.path.join(
        os.path.dirname(__file__),
        "..",
        "..",
        ".."
    )
)

ML_DIR = os.path.join(ROOT, "ml")

for path in [ROOT, ML_DIR]:
    if path not in sys.path:
        sys.path.append(path)

# ----------------------------------
# Import Hybrid AI
# ----------------------------------

from ml.recommender.hybrid_ranker import hybrid_recommend

# ----------------------------------
# Router
# ----------------------------------

router = APIRouter(
    prefix="/recommend",
    tags=["AI Recommendation"]
)

# ----------------------------------
# Request Model
# ----------------------------------

class RecommendationRequest(BaseModel):
    title: str
    top_k: int = 10


# ----------------------------------
# Endpoint
# ----------------------------------

@router.post("/")
def recommend_movies(request: RecommendationRequest):

    response = hybrid_recommend(
        request.title,
        request.top_k
    )

    mode = response.get("mode", "hybrid")
    resolved = response.get("resolved")

    if mode == "movie" and resolved:

        explanation = (
            f'You selected "{resolved["title"]}". '
            "The AI analyzed similar genres, themes, storyline, audience preferences "
            "and overall movie similarity before ranking the recommendations."
        )

    elif mode == "hybrid":

        explanation = (
            f'Your search "{request.title}" was interpreted using Hybrid AI. '
            "The engine combined semantic understanding, BM25 keyword search, "
            "fuzzy matching and popularity signals to produce these recommendations."
        )

    else:

        explanation = (
            "Recommendations generated by the AI recommendation engine."
        )

    return {
        **response,
        "ai_summary": {
            "title": "🤖 AI Analysis",
            "description": explanation
        }
    }